cv/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    
    path('', views.homepage, name = 'homepage'),
    path('<int:id>/', views.resume, name= 'resume'),
    path('list/', views.cv_list, name = 'cv_list'),
]

demo/urls.py
from django.urls import path
from . import views

app_name = 'demo'

urlpatterns = [

	path('list/', views.product_list, name='list'),
	path('list/<int:pk>', views.product_detail, name='detail'),
	path('list/<int:pk>/add/', views.add_quantity, name = 'add_quantity'),
	path('list/<int:pk>/delete/', views.delete_quantity, name = 'delete_quantity'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cv.urls')),
    path('', include('shop.urls')),
    path('demo/', include('demo.urls')),
]

shop/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    
    path('shop/', views.index, name = 'shop'),
    
]

cv/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
	name = models.CharField(max_length=255)
	email = models.EmailField(max_length=255)
	phone = models.CharField(max_length=255)
	summary = models.TextField(max_length=4000)
	university = models.CharField(max_length=255)
	school = models.CharField(max_length=255)
	work_experience = models.TextField(max_length=4000)

	def __str__(self):
		return self.name 

demo/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	name = models.CharField(max_length=250)
	price = models.IntegerField()
	quantity = models.IntegerField()

	def __str__(self):
		return self.name

gnb/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
	firm_name = models.CharField(max_length=255)
	name = models.CharField(max_length=255)
	address = models.CharField(max_length=255)
	email = models.EmailField(max_length=255)
	phone = models.IntegerField()

	def __str__(self):
		return self.firm_name

class Product(models.Model):
	name = models.CharField(max_length=266)
	size = models.CharField(max_length=255)
	price = models.IntegerField()

	def __str__(self):
		return self.name

		
class Damage(models.Model):
	firm_name = models.ForeignKey(Customer, on_delete = None, related_name='damage_firm_name')
	name = models.ForeignKey(Customer, on_delete = None, related_name='damage_customer_name')
	product = models.ForeignKey(Product, on_delete = None, related_name='damage_product')
	mfg = models.DateTimeField(auto_now=False, auto_now_add=False)
	expiry = models.DateTimeField(auto_now=False, auto_now_add=False)

	def __str__(self):
		return str(self.product)

shop/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	title = models.CharField(max_length=255)
	price = models.FloatField()
	discounter_price = models.FloatField()
	category = models.CharField(max_length=255)
	description = models.TextField(max_length=1000)
	image = models.CharField(max_length=300)

	def __str__(self):
		return self.title

cv/views.py
from django.shortcuts import render
from . models import Profile
import pdfkit
import io
from django.http import HttpResponse
from django.template import loader
# Create your views here.

def homepage(request):
	if request.method == 'POST':
		name = request.POST.get("name", "")
		email = request.POST.get("email", "")
		phone = request.POST.get("phone", "")
		summary = request.POST.get("summary", "")
		university = request.POST.get("university", "")
		school = request.POST.get("school")
		work_experience = request.POST.get("work_experience", "")

		profile = Profile(name = name, email=email, phone = pmmaryhone, summary=su, university = university, school = school, work_experience=work_experience)
		profile.save()

	return render(request, 'homepage.html', {})

def resume(request, id):
	user_profile = Profile.objects.get(pk=id)
	template = loader.get_template('includes/resume.html')
	html = template.render({'user_profile':user_profile})
	options = {

		'page-size':'Letter',
		'encoding': 'UTF-8',
	}
	pdf = pdfkit.from_string(html, False, options)
	response = HttpResponse(pdf, content_type = 'application/pdf')
	response['Content-Disposition']= 'attachment'
	filename = 'resume.pdf'
	return response

def cv_list(request):
	user_profile = Profile.objects.all()
	return render(request, 'cv_list.html', {'user_profile':user_profile})

demo/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from .models import Product
from django.urls import reverse
# Create your views here.
def product_list(request):
	products = Product.objects.all()
	return render(request, 'product_list.html', {'products':products})

def product_detail(request, pk):
	product = get_object_or_404(Product, pk=pk)
	return render(request, 'product_detail.html', {'product':product})


def add_quantity(request,pk):
	if request.method == 'POST':
		product = get_object_or_404(Product, pk=pk)
		quantity = request.POST.get('quantity')
		int_quantity = int(quantity)
		product.quantity += int_quantity
		product.save()
		return redirect('/demo/list/' + str(product.id))

def delete_quantity(request, pk):
	if request.method == 'POST':
		product = get_object_or_404(Product,pk=pk)
		quantity = request.POST.get('quantity')
		int_quantity = int(quantity)
		product.quantity -=int_quantity
		product.save()
		return redirect('/demo/list/' + str(product.id))

gnb/views.py
from django.shortcuts import render

# Create your views here.
def add_product(request,id):
	if request.method == 'POST':
		quantity = request.POST.get('quantity')
		Product.quantity += quantity

		

shop/views.py
from django.shortcuts import render
from . models import Product 
from django.core.paginator import Paginator

# Create your views here.

def index(request):
	products = Product.objects.all()

	#Search code

	item_name = request.GET.get('item_name')
	if item_name != '' and item_name is not None:
		products = products.filter(title__icontains=item_name)

	#Pagination Code
	paginator = Paginator(products, 3)
	page = request.GET.get('page')
	products = paginator.get_page(page)

	return render(request, 'index.html', {'products':products})

cv/templates/cv_list.html
<!DOCTYPE html>
<html>
<head>
	<title>Resume List</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
	{% include "includes/navbar.html" %}
		<div class="container">
			<div class="row m-5">
				<div class="col-md-12">
					<h2>Current User Resume</h2>
				</div>
			</div>
			{% for profile in user_profile %}
			<div class="row">
				<div class="col-md-6">
					{{profile.name}}
				</div>
				<div class="col-md-6">
					<a href="/{{profile.id}}" class="btn btn-warning">Download CV</a>
				</div>
			</div>
			<hr>
			<br>
			{% endfor %}
		</div>
</body>
</html>

cv/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>CV Generator</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>


	{% include 'includes/navbar.html' %}

	<div class="container">
		<div class="row">
			<div class="col-md-7 mt-5">
				{% include "includes/forms.html" %}
			</div>
			
		</div>
		
	</div>


</body>
</html>

cv/templates/includes/forms.html
<form method="POST" action=".">
  {% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name", name="name" placeholder="Enter Your name..">
  </div>

  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email", name="email" placeholder="Enter Your Email..">
  </div>

  <div class="form-group">
    <label for="phone">Phone</label>
    <input type="text" class="form-control" id="phone", name="phone" placeholder="Enter Your Phone..">
  </div>

  <div class="form-group">
    <label for="summary">Summary</label>
    <textarea class="form-control" id="summary", name="summary" placeholder="Something About You!"> </textarea>
  </div>

  <div class="form-group">
    <label for="university">University</label>
    <input type="text" class="form-control" id="unitversity", name="university" placeholder="Enter Your University..">
  </div>

  <div class="form-group">
    <label for="school">School</label>
    <input type="text" class="form-control" id="school", name="school" placeholder="Enter Your School..">
  </div>


  <div class="form-group">
    <label for="work_experience">Work Experience</label>
    <input type="text" class="form-control" id="work_experience", name="work_experience" placeholder="Enter Your Work Experience..">
  </div>


  <div class="form-group">
    <label for="skills">Skills</label>
    <input type="skills" class="form-control" id="skills", name="skills" placeholder="Enter Your Skills..">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

cv/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'homepage' %}">CV Generator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cv_list' %}">Resume <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

cv/templates/includes/resume.html
<!DOCTYPE html>
<html>
<head>
	<title>Resume</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-7 mt-5">

		<h1>Resume</h1>

		<hr>
		<br>

		<h2>{{user_profile.name}}</h2>
		<h2>{{user_profile.email}}</h2>
		<h2>{{user_profile.phone}}</h2>
		<hr>
		<br>
		<p>Summary</p>
		<p>{{user_profile.summary}}</p>
		<p>Qualification</p>
			<ul>
				<li>{{user_profile.school}}</li>
				<li>{{user_profile.university}}</li>
			</ul>
		<p>Work Experience</p>
			<p>{{user_profile.work_experience}}</p>		
			</div>
			
		</div>
		
	</div>
</body>
</html>

demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

   
  </head>
  <body>

    <div class="container my-4">
        {% block content %}
          
        {% endblock %} 
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

demo/templates/product_detail.html
{% extends "base.html" %}

{% block content %}
	<h3>Name: {{product.name}}</h3>
	<h5>Quantity: {{product.quantity}}cs</h5>
	<p>Price: Rs.{{product.price}}</p>
{# Product Add form #}
<form action="{% url 'demo:add_quantity' product.id %}" method="POST">
	{% csrf_token %}
  Quantity To Add:  <input type="number" name="quantity" min="1" max="100">
  <input class="btn btn-success" type="submit" value="Add">
</form>

{# Product Delete form #}
<br>
<br>
<form method="POST" action="{% url 'demo:delete_quantity' product.id %}">
	{% csrf_token %}
	Quantity To Delete: <input type="number" name="quantity" min="1" max="100">
	<input type="submit" value="Delete" class="btn btn-success">
</form>


<a href="{% url 'demo:list' %}" class="btn btn-primary my-4" role="button">Back To Products</a>
{% endblock content %}

{# {% url 'demo:add_quantity' product.id %} #}

demo/templates/product_list.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
          {% for product in products %}
          <div class="col-md-4">
            <h3>{{product.name}}</h3>
            <p>Quantity: {{product.quantity}} <span> Price:Rs.{{product.price}}</span> </p> 
           <a href="{% url 'demo:detail' product.id %}" class="btn btn-primary">Details</a>
          </div>
          {% endfor %}
        </div> 
{% endblock content %}

gnb/templates/product_detail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>



<form>

	<input type="text" name="quantiy", value="Enter the amount to add or delete">
	<input type="submit" value="Submit">

</form>


</body>
</html>

shop/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>SHOP</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">

</head>
<body>

<div class="container">

	<div class="row mt-4">
		<div class="col-md-12">
			<form class="card card-sm">
				<div class="card-body row no-gutters align-items-center">
					<div class="col">
						<input type="search" name="item_name" placeholder="Search for products" class="form-control form-control-borderless">
					</div>
					<div class="col-auto">
						<button class="btn btn-success" type="submit">Search</button>
					</div>
				</div>
			</form>
			
		</div>
		
	</div>

	<div class="row mt-5">
	{% for product in products %}
		<div class="col-md-4">	
			<div class="card" style="width: 18rem;">
			  <img src="{{product.image}}" class="card-img-top" alt="...">
			  <div class="card-body">
			    <h5 class="card-title">{{product.title}}</h5>
			    <p class="card-text"><span>&#8377 </span>{{product.price}}</p>
			    <a href="#" class="btn btn-primary">View</a>
			  </div>
			</div>
		</div>
			
		{% endfor %}
	</div>
	
	<div class="row mt-4 ml-5">
		<div class="col-md-3 offset-md-4">
			<ul class="pagination">
				{% if products.has_previous %}

					<li class="page-item">
						<a class="page-link" href="?page={{products.previous_page_number}}">Back</a>
					</li>
					
				{% endif %}

					<li class="page-item active">
						<a class="page-link" href="?page={{products.number}}">Current</a>
					</li>

				{% if products.has_next %}

					<li class="page-item">
						<a class="page-link" href="?page={{products.next_page_number}}">Next</a>
						
					</li>
					
				{% endif %}
			</ul>

			
		</div>
		
	</div>
	
</div>

















</body>
</html>